spring:
  application:
    name: lija
  datasource:
    generate-unique-name: false
    name: lija
    hikari:
      maximum-pool-size: 100
      connection-timeout: 15000
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /assets/**

server:
  tomcat:
    connection-timeout: 2s

sync: #milliseconds
  duration: 7000
  sleep: 200

lobby:
  message:
    max: 30
  entry:
    max: 12
  message.lifetime: 20
  hook-pool.tick.frequency: 1s

game:
  message.lifetime: 20

socket:
  host: 0.0.0.0
  port: 9092

memo: #seconds
  watcher:
    timeout: 6
  username:
    timeout: 10
  hook:
    timeout: 6
  finisher-lock:
    timeout: 30
ai:
  server: false
  use: remote
  crafty:
    exec-path: C:\Leo\Arena\Engines\stockfish_14.1_win_x64_avx2\stockfish_14.1_win_x64_avx2.exe
    book-path:
  remote:
    url:

moretime:
  seconds: 15

async:
  actions:
    core-size: 16
    max-size: 2048
  websockets:
    parallelism: 64
    max-size: 1024
